name: Run Unit Tests

run-name: Test [ ${{ github.event.head_commit.message }} ]

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install JVM for Spark to use
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "22.0.2"

      - name: Install Postgres 14 for psychopg2 to use
        uses: tj-actions/install-postgresql@v3
        with:
          postgresql-version: 14

      - name: Install Unix ODBC for pyodbc to use
        run: |
          sudo apt-get install unixodbc

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Test with pytest
        run: |
          pytest